"""This script analyzes the performance of the Gaussian PSF operator on simulated data (simulated_data/output, generated with simulated_data/simulate.py).

This script can be run through a REPL kernel or as a standalone script.

# Running Spectrex on simulated data

In this notebook we run Spectrex on realistic simulated NIRISS/GR150C WFSS data
(generated by `simulated_data/simulate.py` (which uses a Gaussian) to demonstrate extraction.

These simulations are **not** produced by Spectrex's own forward operator, so the
operator must be built to match the *same* grism calibration the simulations used
(the CRDS `specwcs` files shipped alongside the data), and must include the PSF
convolution the simulations apply. Both fixes live in small notebook-local helper
classes below (`CRDSConfig`, `PSFOperator`) so the library is left untouched.

## Looking at the simulated data `simulated_data/output...`

- folder contains simulated data with a Gaussian PSF profile (FWHM 1.6 px, slightly undersampled).
- For each set we have F115W, F150W, and F200W outputs: `sim_GR150C_<band>_direct.fits`, `sim_GR150C_<band>_grism.fits`
- `truth_catalog.ecsv` contains the positions and fluxes of the simulated sources (and additional labels for validation)

### Analysis tools and functions

We defined conveniently a few classes to help store and manipulate our configuration and results.

### CRDSConfig

The `CRDSConfig` class is a subclass of `InstrumentConfig` that drives a CRDS ``specwcs`` trace correctly.
It is a temporary patch that fixes the Angstrom→micron units and the (col,row)↔(row,col) convention swap;

### PSFOperator

The `PSFOperator` class is a subclass of `JAXOperator` that includes a (Gaussian) PSF convolution.

The internals of Spectrex did not consider the convolution of a PSF, so the
`PSFOperator` is a temporary patch that fixes this.

### SimulationAnalysisConfig & SimulationAnalysisResult

- `SimulationAnalysisConfig`: holds the configuration analysis for a set of bands. This is common across all bands for our simulated data.
- `SimulationAnalysisResult`: holds the results of a single band analysis.

### SpectralBasis

A simple interface to the spectra from the basis library.

## Analysis Pipeline

- `run_band`: is the main analysis function for a given band. It builds a PSF-aware, CRDS-driven operator and fit one grism image and returns a SimulationAnalysisResult`.

###  Pipeline schematics

To analyze a band image (e.g. F150W), we do the following:
- prepare the data
    - we load the simulated band image, we have only order = "+1" here. --> gaussian psf: sigma_psf = fwhm / 2.355 from header
    - we load the source catalog to get the positions of the sources
    - we setup the mapping of tracings for this specific band using CRDS information (wcs) -- `get_grismtrace_from_crds`
    - we get the wavelength range for the order (+1 only here) in the image to help define the wavelength grid for PCA and sensitivity curves
    - Get the sensitivity curve for this band and these wavelengths `get_sensitivity_curve(which_band, wavelengths)`
- prepare the model
    - set the InstrumentConfig that drives a CRDS specwcs trace correctly.
    - Reload the PCA basis from disk (here 10PCs from kurucz atmospheres at R=140, and normalized to eigenvalues)
    - Build the `JaxOperator` (FIXME: numpy operations within)
    - Build the PSF operator `op =PSFOperator(...)` (Gaussian convolution) composed with the previous one.
    - Setup the Solver `JaxProximalSolver`
- Fit the model
    - we internally scale the fluxes to the 90th flux percentile (1e22 -> 1)
    - Solve the optimization problem using the solver `a = solver.solve()` (ravelled images)
- Extract the solution
    - image is the `model = op.apply(a).reshape(...)`
    - extract the spectra `spectra = a.reshape(-1, basis.n_components) @ basis.components.T`
- Analysis/statistics

"""

# %% Cell 1 - imports / setup ----------------------------------------------
import logging
import os
import warnings
from dataclasses import dataclass, field
from glob import glob
from pathlib import Path
from time import time
from typing import Callable, cast

import matplotlib.colors as colors
import matplotlib.pyplot as plt
import numpy as np
import numpy.typing as npt
import yaml
from asdf._asdf import AsdfPackageVersionWarning
from astropy.io import fits
from astropy.table import Table
from grismagic.traces import GrismTrace
from IPython.display import Markdown
from logger import RichLogger
from matplotlib.figure import Figure
from scipy.spatial import cKDTree  # pyright: ignore
from tools import CRDSConfig, direct_extract_source, glob_files, trace_snippet

import spectrex
from spectrex import (
    EigenspectraBasis,
    GaussianPSFOperator,
    JAXProximalSolver,
)
from spectrex.jax_operator import JAXOperator

logger = RichLogger("spectrex.analyze_mock").set_defaults()
logger.setLevel(logging.DEBUG)

warnings.filterwarnings("ignore", category=AsdfPackageVersionWarning)

# Anchor paths to this file's location (works both as a notebook and as a script).
try:
    HERE = Path(__file__).resolve().parent
except NameError:  # running inside a Jupyter kernel
    HERE = Path.cwd()

SIMULATED_DATA = HERE / "simulated_data" / "output"
CONF_DIR: Path = Path("./")
SENS_CONF_DIR: Path = CONF_DIR / "simulated_data" / "SenseConfig"
ORDER_SENS_TAG = {"+1": "p1", "+2": "p2", "+3": "p3", "-1": "m1"}

SEED = 42
rng = np.random.default_rng(SEED)

logger.info("🚀 Spectrex analysis")
logger.info(f"    ℹ️  Using spectrex {spectrex.__version__}")
logger.debug(f"   SIMULATED_DATA={SIMULATED_DATA}")
logger.debug(f"   CONF_DIR={CONF_DIR}")
logger.debug(f"   SENS_CONF_DIR={SENS_CONF_DIR}")
logger.debug(f"   SEED={SEED}")
# %% Cell - setup
# We define convenient functions/classes for working with the simulated data.


@dataclass
class SpectralBasis:
    """A class to manipulate the spectral basis (original spectra)."""

    original_spectra_path: Path
    """Original spectra path (CSV format, last row = wavelength in Angstrom)"""

    def __post_init__(self):
        data = np.loadtxt(
            self.original_spectra_path, delimiter=",", dtype=float
        )
        self._wave = np.asarray(data[-1], dtype=float)  # Angstrom (last row)
        self._spectra = np.asarray(
            data[:-1], dtype=float
        )  # (n_templates, n_wave)
        # enforce ascending wavelength order
        _idx = np.argsort(self._wave)
        self._wave = self._wave[_idx]
        self._spectra = self._spectra[:, _idx]

    @property
    def λ_AA(self) -> np.ndarray:
        """Wavelength in Angstrom"""
        return self._wave

    @property
    def λ_um(self) -> np.ndarray:
        """Wavelength in micrometers"""
        return self.λ_AA * 1e-4

    @property
    def spectra(self) -> np.ndarray:
        """Spectra (n_templates, n_wave)"""
        return self._spectra


def load_sensitivity(
    filt: str, order: str, sens_dir: str | Path = SENS_CONF_DIR
) -> tuple[Callable[[npt.NDArray[np.float64]], npt.NDArray[np.float64]], Path]:
    """Interpolator for the aXe ETC sensitivity curve (Angstrom in, 0 outside).

    Parameters
    ----------
    filt : str
        Filter name (e.g. "F150W").
    order : str
        Order of the filter (e.g. "+1").
    sens_dir : str or Path, optional
        Directory containing the sensitivity curve files.
        Defaults to `SENS_CONF_DIR`.

    Returns
    -------
    Callable[[npt.NDArray[np.float64]], npt.NDArray[np.float64]]
        Interpolator function for the sensitivity curve.
    Path
        Path to the sensitivity curve file.
    """
    tag = ORDER_SENS_TAG.get(order)
    if tag is None:
        raise ValueError(
            f"No sensitivity curve available for order {order!r}; "
            f"supported orders: {list(ORDER_SENS_TAG)}"
        )
    logger.info(f"Loading sensitivity curve for {filt} {order} ({tag})...")
    logger.debug(f"sens_dir: {sens_dir}")
    logger.debug(
        f"glob pattern: {sens_dir}/**/NIRISS.GR150C.{filt}.{int(order)}.*.sens.fits"
    )

    path = Path(
        glob(f"{sens_dir}/**/NIRISS.GR150C.{filt}.{int(order)}.*.sens.fits")[0]
    )
    logger.debug(
        f"path: {sens_dir}/**/NIRISS.GR150C.{filt}.{int(order)}.*.sens.fits"
    )

    if not path.exists():
        raise FileNotFoundError(f"Sensitivity curve not found: {path}")

    with fits.open(path) as hdul:
        hdu = cast(fits.BinTableHDU, hdul[1])
        λs = np.asarray(hdu.data["WAVELENGTH"], dtype=float)
        sens = np.asarray(hdu.data["SENSITIVITY"], dtype=float)

    def interp(λ_AA):
        return np.interp(λ_AA, λs, sens, left=0.0, right=0.0)

    return interp, path


@dataclass
class SimulationAnalysisConfig:
    """Configuration for the simulation analysis."""

    basepath: Path
    """The base folder path to the simulation data."""
    direct_image: Path
    """The path to the direct image."""
    grism_image: Path
    """The path to the grism image."""
    catalog: Path
    """The path to the catalog."""
    simulation_configuration: dict = field(default_factory=dict)
    """The simulation configuration."""

    def __post_init__(self):
        assert self.direct_image.exists(), (
            f"Direct image not found: {self.direct_image}"
        )
        assert self.grism_image.exists(), (
            f"Grism image not found: {self.grism_image}"
        )
        assert self.catalog.exists(), f"Catalog not found: {self.catalog}"

    @classmethod
    def from_path(
        cls, basepath: Path, which_band: str
    ) -> "SimulationAnalysisConfig":
        """Get the paths to the simulated input data.

        Just a convenient loading function
        Data are stored in the `SIMULATED_DATA/output_{psf_type}/` directory as
        `sim_GR150C_{which_band}_{grism,direct}.fits

        Parameters
        ----------
        which_band : str
            The band to get the paths for.
        """
        with open(basepath / "simulation_configuration.yaml", "r") as f:
            conf = yaml.safe_load(f)

        return cls(
            basepath=basepath,
            direct_image=basepath / f"sim_GR150C_{which_band}_direct.fits",
            grism_image=basepath / f"sim_GR150C_{which_band}_grism.fits",
            catalog=basepath / "truth_catalog.ecsv",
            simulation_configuration=conf,
        )

    @property
    def orders(self):
        """The orders to use for the simulation."""
        return self.simulation_configuration["orders"]

    def get_grismtrace_from_crds(
        self,
        which_band: str,
    ) -> GrismTrace:
        """Get the grism trace from a CRDS specwcs file."""

        specwcs_file = glob_files(
            self.basepath, f"jwst_niriss_specwcs_*.GR150C.{which_band}.asdf"
        )[0]
        wavelength_file = glob_files(
            self.basepath, "jwst_niriss_wavelengthrange_0002.asdf"
        )[0]

        trace = GrismTrace.from_crds(
            str(specwcs_file),
            filter_name=which_band,
            wavelengthrange_file=str(wavelength_file),
            instrument="niriss",
        )
        return trace

    def get_sensitivity_curves(
        self, which_band: str, λ_AA: np.ndarray
    ) -> dict[str, np.ndarray]:
        """extract the sensitivity curve of that band interpolated at that wavelength

        Parameters
        ----------
        which_band : str
            The band to extract the sensitivity curve for.
        λ_AA : np.ndarray
            The wavelengths to interpolate the sensitivity curve at.

        Returns
        -------
        dict[str, np.ndarray]
            The sensitivity curve interpolated at the given wavelengths.
        """
        sensitivity = {}
        for order in self.orders:
            interp, path = load_sensitivity(
                which_band, order, sens_dir=SENS_CONF_DIR
            )
            sensitivity[order] = interp(λ_AA)
        return sensitivity


@dataclass
class AnalysisResults:
    """Bookkeeping for the simulation analysis results."""

    config: SimulationAnalysisConfig
    """Simulation analysis configuration information"""
    band: str
    """The band used for the analysis"""
    n_sources: int
    """The number of sources used in the analysis"""
    λ_AA: np.ndarray
    """The wavelengths used for the analysis in Angstroms"""
    model_grism: np.ndarray
    """The predicted model grism image (n_pixels x n_pixels)"""
    model_spectra: np.ndarray
    """The predicted model spectra (n_sources x n_wavelengths)"""
    model_fluxes: np.ndarray
    """The predicted model fluxes (n_sources)"""
    observed_grism: np.ndarray
    """The observed grism image (n_pixels x n_pixels)"""
    source_catalog: Table
    """The source catalog used for the analysis"""
    operator: JAXOperator
    """The operator used for the analysis"""
    sensitivity_curves: dict[str, np.ndarray]
    """The sensitivity curves {n_orders: n_wavelengths)"""
    other: dict = field(default_factory=dict)
    """Any other results or metadata from the analysis. Garbage collector here"""

    @property
    def observed_fluxes(self) -> np.ndarray:
        """The observed fluxes from the source catalog (n_sources)"""
        return self.source_catalog[f"flux_{self.band}"].data.astype(float)  # pyright: ignore

    @property
    def source_positions(self) -> np.ndarray:
        """The source positions from the source catalog (n_sources x 2)"""
        cat = self.source_catalog
        X = cat["x"].data.astype(float)  # pyright: ignore
        Y = cat["y"].data.astype(float)  # pyright: ignore
        return np.column_stack([Y, X])

    def grism_relative_residuals(self) -> float:
        r"""compute the image relative residual

        .. math::

            \\frac{\|model_{grism} - observed_{grism}\|}{\|observed_{grism}\|}

        """
        return float(
            np.linalg.norm(self.model_grism - self.observed_grism)
            / np.linalg.norm(self.observed_grism)
        )

    @property
    def residual_image(self) -> np.ndarray:
        # Normalise by a *global* robust flux scale, not per-pixel max(model, 1).
        # The old per-pixel form blew up every low-flux pixel (trace wings, gaps
        # between sources, background) to the raw data value, saturating the
        # residual colormap and painting bright "edges" that read as the model
        # being truncated.  With a global scale the residual is in units of
        # "fraction of typical bright flux", so wings (~1e-8 of peak) vanish
        # while genuine few-percent fit errors stay visible.
        obs = self.observed_grism
        positive = obs[obs > 0]
        scale = float(np.nanpercentile(positive, 99)) if positive.size else 1.0
        scale = max(scale, 1.0)
        return (obs - self.model_grism) / scale


def run_band(
    which_band: str,
    max_iter: int = 300,
    lam: float = 0.0,
):
    """Build a PSF-aware, CRDS-driven operator and fit one grism image.

    Returns a dict with the model, reconstructed spectra and a flux-recovery
    statistic against the truth catalog.
    """
    logger.info(f"🚀 Running band {which_band}")

    logger.info(
        f"Reading simulated input data information from {SIMULATED_DATA}"
    )
    simconfig = SimulationAnalysisConfig.from_path(SIMULATED_DATA, which_band)
    logger.debug(
        f"   direct image: {simconfig.direct_image} (we don't use it here)"
    )
    logger.debug(f"   grism image: {simconfig.grism_image}")
    logger.debug(f"   catalog: {simconfig.catalog}")
    logger.debug(
        f"   simulation configuration: {simconfig.simulation_configuration}"
    )
    logger.debug(f"   Simulations are for order(s): {simconfig.orders}")

    # we need to setup the mapping of tracings for this specific band
    logger.info(f"Getting the GrismTrace instance for band {which_band}")
    trace = simconfig.get_grismtrace_from_crds(which_band)

    # Get the wavelength range for the order in the image
    λlo_um, λhi_um = trace._lam_range(simconfig.orders[0], None, None)
    if λlo_um is None or λhi_um is None:
        raise ValueError("λlo_um or λhi_um is None")
    logger.debug(
        f"   {which_band} wavelength range for order {simconfig.orders[0]}: {λlo_um} - {λhi_um}"
    )
    λ_AA = np.linspace(
        max(float(λlo_um) * 1e4, 7000.0),
        # clamp to the PCA basis max wavelength (regenerated kurucz_pca.csv
        # spans 0.7–2.3 µm = 7000–23000 Å); otherwise from_csv raises.
        min(float(λhi_um) * 1e4, 23000.0),
        150,
    )
    logger.debug(
        f"   Assumming 150 linear samples of wavelengths: {λ_AA.shape} values"
    )

    # Get the sensitivity curve for this band and these wavelengths
    logger.info(
        f"Getting the sensitivity curve for band {which_band} and order {simconfig.orders[0]}"
    )
    sensitivity_curves = simconfig.get_sensitivity_curves(which_band, λ_AA)

    # Get the dispersed image / the grism image
    logger.info(f"Reading grism image {simconfig.grism_image}")
    with fits.open(simconfig.grism_image) as hdul:
        hdu = cast(fits.PrimaryHDU, hdul[0])
        grism = np.asarray(hdu.data, dtype=float)
        fwhm = float(hdu.header.get("FWHM", 1.6))  # pyright: ignore
    n_rows, n_cols = grism.shape
    sigma_psf = fwhm / 2.355  # 2 sqrt(2*ln(2))  -- Gaussian conversion factor
    logger.debug(f"    Image shape: {n_rows} x {n_cols}")
    logger.debug(f"    PSF sigma: {sigma_psf}")

    # Get the source catalog to get the source positions
    logger.info(f"Reading source catalog {simconfig.catalog}")
    cat = Table.read(simconfig.catalog)
    X = cat["x"].data.astype(float)  # column
    Y = cat["y"].data.astype(float)  # row
    n_sources = len(X)
    source_positions = np.column_stack([Y, X])
    logger.debug(f"    Found {n_sources} sources in catalog")

    logger.info("Model preparation...")
    logger.debug("    Setting up CRDSConfig with the above")

    config = CRDSConfig(
        grism="GR150C",
        filter_name=which_band,
        wavelengths=λ_AA,
        orders=simconfig.orders,
        sensitivity=sensitivity_curves,
        trace=trace,
        psf_stamp_size=7,
    )

    # Get the eigenspectra basis. This is a PCA basis of Kurucz spectra to represent stars
    eigenspectra_source = simconfig.basepath / "kurucz_pca.csv"
    logger.info(f"Getting the eigenspectra basis from {eigenspectra_source}")
    # Fixed PCA to include the mean spectrum data[:, 1]
    basis = EigenspectraBasis.from_csv(eigenspectra_source, λ_AA)

    # composing operators: PSF-aware forward model
    logger.info("Building Image model operator (GaussianPSFOperator)")
    # Build the PSF *into* the forward model by scattering a 2D Gaussian stamp
    # at each (sub-pixel) trace point — this matches the simulation's forward
    # model and avoids the sub-pixel aliasing a point delta + Gaussian blur
    # leaves along the dispersion direction.
    op = GaussianPSFOperator.build(
        config,
        basis,
        grism.shape,
        source_positions,
        psf_sigma=sigma_psf,
        stamp_size=config.psf_stamp_size,
    )

    print("Fitting...")
    logger.info(
        f"Building solver JAXProximalSolver(max_iter={max_iter}, lam={lam})"
    )
    # use the JAX solver to fit the image
    solver = JAXProximalSolver(
        op, noise_model=None, lam=lam, max_iter=max_iter
    )
    # internally we solve on the flat array
    f_flat = grism.ravel().astype(float)
    # scale normalization needed for the solver stability
    scale = float(np.percentile(grism[grism > 0], 90))

    logger.info("Solving for image solution...")
    _fitting_start = time()
    a = solver.solve(f_flat / scale) * scale
    _fitting_end = time()
    logger.info(
        f"    Fitting Done. (took {_fitting_end - _fitting_start:.2f}s)"
    )

    logger.info("Extracting spectra...")
    # compute the psf convolved model image
    model = op.apply(a).astype(float).reshape(n_rows, n_cols)
    # compute the spectra source by source
    coeff = a.reshape(-1, basis.n_components)
    spectra = basis.reconstruct(coeff)
    # sum over the wavelength axis to get the predicted fluxes
    # FIXME: flux_proxy = np.trapz(spectra, x=wavelengths, axis=1)
    flux_proxy = spectra.sum(axis=1)

    result = AnalysisResults(
        config=simconfig,
        band=which_band,
        n_sources=n_sources,
        λ_AA=λ_AA,
        model_grism=model,
        model_spectra=spectra,
        model_fluxes=flux_proxy,
        observed_grism=grism,
        source_catalog=cat,
        operator=op,
        sensitivity_curves=sensitivity_curves,
    )

    # Compute some performance statistics / values
    logger.info("Finding and flagging isolated sources.")
    # find isolated sources to help comparison later
    # isolated source = no nearby neighbors (within 60 pixels)
    tree = cKDTree(np.column_stack([X, Y]))
    d2, _ = tree.query(np.column_stack([X, Y]), k=2)
    isolated = d2[:, 1] > 60  # arbitrary threshold
    result.other["is_isolated"] = isolated
    logger.info(f"Found {isolated.astype(int).sum()} isolated sources.")

    # blind direct extraction (isolated sources only)
    logger.info("Extracting spectra from the grism image when isolated...")
    direct = np.full((n_sources, len(λ_AA)), np.nan)
    for k in np.where(isolated)[0]:
        direct[k] = direct_extract_source(
            grism,
            op._trace_indices[k, 0],  # pyright: ignore
            sigma_psf,
            n_rows,
            n_cols,
        )
    result.other["isolated_direct_spectra"] = direct

    logger.info("Extracting original kurucz spectra per simulated source...")
    kurucz_basis = SpectralBasis(
        original_spectra_path=simconfig.basepath / "kurucz_spectra.csv"
    )
    ki = cat["kurucz_index"].data.astype(int)
    orig = np.empty((n_sources, len(λ_AA)))
    for k in range(n_sources):
        orig[k] = np.interp(
            λ_AA, kurucz_basis.λ_AA, kurucz_basis.spectra[ki[k]]
        )
    result.other["original_spectra"] = orig

    # fit proxy vs. truth for isolated sources
    # compute the linear fit to the proxy vs. truth for isolated sources
    # compute the R^2 value for the fit
    logger.info("Fitting proxy vs. truth for isolated sources...")
    truth_flux = result.observed_fluxes
    c = np.polyfit(flux_proxy[isolated], truth_flux[isolated], 1)[0]
    pred = c * flux_proxy[isolated]
    r2 = 1.0 - np.sum((truth_flux[isolated] - pred) ** 2) / np.sum(
        (truth_flux[isolated] - truth_flux[isolated].mean()) ** 2
    )
    result.other["r2_isolated"] = r2
    logger.info(f"    R^2 = {r2:.3f}")

    # add bookkeeping
    result.other.update(
        {
            "a": a,
            "base_op": op,
            "basis": basis,
            "op": op,
            "c": c,
            "sigma_psf": sigma_psf,
            "n_rows": n_rows,
            "n_cols": n_cols,
        }
    )

    return result


# %% Cell - review figures -------------------------------------------------
def _corr(a, b):
    """Correlation over finite, positive elements (robust to NaNs/zeros)."""
    a = np.asarray(a, float)
    b = np.asarray(b, float)
    m = np.isfinite(a) & np.isfinite(b) & (a > 0) & (b > 0)
    if m.sum() < 3:
        return float("nan")
    return float(np.corrcoef(a[m], b[m])[0, 1])


def _safe_norm(img, kind="log", percs=(20, 99.5)):
    """Display norm that never raises on degenerate (e.g. background) ranges."""
    vmin, vmax = np.nanpercentile(
        np.where(np.isfinite(img), img, np.nan), percs
    )
    if not (np.isfinite(vmin) and np.isfinite(vmax) and vmax > vmin):
        return colors.Normalize(vmin=np.nanmin(img), vmax=np.nanmax(img))
    if kind == "log":
        lo = max(vmin, 1e-3)
        if vmax <= lo:
            return colors.Normalize(vmin=vmin, vmax=vmax)
        return colors.LogNorm(vmin=lo, vmax=vmax)
    return colors.Normalize(vmin=vmin, vmax=vmax)


def make_review_figures(
    res, band, outdir="figures", close_figures=True, seed: int | None = None
) -> list[str] | tuple[list[Figure], list[str]]:
    """Write the four standard review figures for one band.

    * fig1: full-frame data / model / residual
    * fig2: zoomed segment of one bright isolated source's trace
    * fig3: recovered vs true (Kurucz) spectrum for 4 isolated sources
    * fig4: observed (direct extraction x sensitivity) vs model prediction
    * fig5: grism image snippet per source

    Returns the list of saved file paths.
    """
    os.makedirs(outdir, exist_ok=True)
    obs = res.observed_grism
    mod = res.model_grism
    resid = res.residual_image
    shape = obs.shape
    wav = res.λ_AA
    saved = []

    figures = []

    # ---- Fig 1: full-frame data / model / residual ----
    fig, axes = plt.subplots(1, 3, figsize=(16, 5), sharex=True, sharey=True)
    for ax, img, title in zip(
        axes,
        [obs, mod, resid],
        ["data", "model", "residual (obs-model)/p99(obs)"],
    ):
        if title.startswith("residual"):
            im_ = ax.imshow(
                img,
                origin="lower",
                cmap="RdBu",
                norm=colors.CenteredNorm(vcenter=0, halfrange=0.05),
            )
        else:
            vmin, vmax = np.nanpercentile(obs, [16, 84])
            im_ = ax.imshow(
                img,
                origin="lower",
                cmap="gray",
                norm=colors.AsinhNorm(vmin=vmin, vmax=vmax),
            )
        fig.colorbar(im_, ax=ax)
        ax.set_title(title, fontsize="large", fontweight="bold")
    plt.tight_layout()
    p = os.path.join(outdir, f"fig1_{band}.png")
    fig.savefig(p, bbox_inches="tight")
    saved.append(p)
    figures.append(fig)

    # ---- Fig 2: zoomed trace *segment* for a bright isolated source ----
    iso = res.other["is_isolated"]
    flux = res.observed_fluxes
    cand = np.where(iso)[0]
    k = int(cand[np.argmax(flux[cand])])
    op = res.operator
    n_pix = shape[0] * shape[1]
    pix = np.asarray(op._trace_indices[k, 0])
    valid = np.where(pix < n_pix)[0]
    # central ~25% of the (valid) trace, so the window is a real zoom
    lo = valid[len(valid) // 2 - len(valid) // 8]
    hi = valid[len(valid) // 2 + len(valid) // 8]
    seg = pix[lo : hi + 1]
    rows = seg // shape[1]
    cols = seg % shape[1]
    win = 6
    yy0 = max(0, int(rows.min()) - win)
    yy1 = min(shape[0], int(rows.max()) + win + 1)
    xx0 = max(0, int(cols.min()) - win)
    xx1 = min(shape[1], int(cols.max()) + win + 1)
    cd = obs[yy0:yy1, xx0:xx1]
    cm = mod[yy0:yy1, xx0:xx1]
    cr = resid[yy0:yy1, xx0:xx1]
    fig, axes = plt.subplots(1, 3, figsize=(12, 4.2), sharex=True, sharey=True)
    norm = _safe_norm(cd)
    for ax, img, t in zip(axes, [cd, cm, cr], ["Data", "Model", "Residual"]):
        if t == "Residual":
            im = ax.imshow(
                img,
                origin="lower",
                cmap="RdBu",
                norm=colors.CenteredNorm(vcenter=0, halfrange=0.05),
            )
        else:
            im = ax.imshow(
                np.where(np.isfinite(img) & (img > 0), img, 1e-10),
                origin="lower",
                cmap="gray",
                norm=norm,
            )
        plt.colorbar(im, ax=ax, orientation="horizontal")
        ax.set_title(t)
    plt.tight_layout()
    plt.suptitle(
        f"{band} — source {k} (zoomed trace segment)",
        y=1.05,
        fontsize="large",
        fontweight="bold",
    )
    p = os.path.join(outdir, f"fig2_{band}.png")
    fig.savefig(p, bbox_inches="tight")
    saved.append(p)
    figures.append(fig)

    ### COMMON TO Fig 3:5
    orig = res.other["original_spectra"]
    sp = res.model_spectra
    idx = np.where(iso)[0]
    if seed is None:
        picks = list(idx[np.argsort(flux[idx])[::-1][:4]])
    else:
        rng = np.random.default_rng(seed)
        picks = list(rng.choice(idx, 4, replace=False))

    # ---- Fig 3: recovered vs true (Kurucz) spectrum ----

    fig, axes = plt.subplots(2, 4, figsize=(18, 8), sharex=True)
    for j, kk in enumerate(picks):
        rec = sp[kk]
        tru = orig[kk]
        cont = np.median(tru[tru > 0])
        rec_med = np.median(rec[rec > 0])
        rec_s = rec * (cont / rec_med) if rec_med > 0 else rec
        c = _corr(rec_s / cont, tru / cont)
        axes[0, j].plot(wav, tru / cont, "k-", lw=1.4, label="true (Kurucz)")
        axes[0, j].plot(wav, rec_s / cont, "C1--", lw=1.2, label="recovered")
        axes[0, j].set_title(f"src {kk}  corr={c:.2f}")
        axes[0, j].legend(fontsize=7)
        axes[1, j].plot(wav, (rec_s - tru) / cont, color="C1", lw=1.0)
        axes[1, j].axhline(0, color="k", lw=0.6)
        axes[1, j].set_xlabel(
            "wavelength [A]", fontsize="large", fontweight="bold"
        )
        if j == 0:
            axes[0, j].set_ylabel(
                "flux / continuum", fontsize="large", fontweight="bold"
            )
            axes[1, j].set_ylabel(
                "resid / continuum", fontsize="large", fontweight="bold"
            )
    fig.suptitle(
        f"{band}: reconstructed vs true spectrum (4 isolated sources)",
        fontsize="large",
        fontweight="bold",
    )
    plt.tight_layout()
    p = os.path.join(outdir, f"fig3_{band}.png")
    fig.savefig(p, bbox_inches="tight")
    saved.append(p)
    figures.append(fig)

    # ---- Fig 4: observed (direct extraction x sensitivity) vs model ----
    # direct_extract_source returns image flux = spectrum x sensitivity; the
    # model prediction in the same units is model_spectra x sensitivity.
    direct = res.other["isolated_direct_spectra"]
    sens = res.sensitivity_curves["+1"]
    model_flux = sp * sens[None, :]
    true_flux = orig * sens[None, :]

    fig, axes = plt.subplots(2, 4, figsize=(18, 8), sharex=True)
    for j, kk in enumerate(picks):
        obs_k = direct[kk]
        mod_k = model_flux[kk]
        tru_k = true_flux[kk]
        on = np.nanmedian(obs_k[obs_k > 0]) or 1.0
        mn = np.nanmedian(mod_k[mod_k > 0]) or 1.0
        tn = np.nanmedian(tru_k[tru_k > 0]) or 1.0
        c = _corr(obs_k / on, mod_k / mn)
        axes[0, j].plot(wav, tru_k / tn, "k-", lw=1.3, label="true x sens")
        axes[0, j].plot(wav, mod_k / mn, "C0-", lw=1.1, label="model x sens")
        axes[0, j].plot(
            wav, obs_k / on, "C1.", ms=3, alpha=0.7, label="observed (direct)"
        )
        axes[0, j].set_title(f"src {kk}  corr(obs,model)={c:.2f}")
        axes[0, j].legend(fontsize=7)
        axes[1, j].plot(wav, (obs_k / on) - (mod_k / mn), color="C1", lw=1.0)
        axes[1, j].axhline(0, color="k", lw=0.6)
        axes[1, j].set_xlabel("wavelength [A]")
        if j == 0:
            axes[0, j].set_ylabel(
                "(flux x sens) / med", fontsize="large", fontweight="bold"
            )
            axes[1, j].set_ylabel(
                "obs - model (norm)", fontsize="large", fontweight="bold"
            )
    fig.suptitle(
        f"{band}: observed (direct x sensitivity) vs model in likelihood units",
        fontsize="large",
        fontweight="bold",
    )
    plt.tight_layout()
    p = os.path.join(outdir, f"fig4_{band}.png")
    fig.savefig(p, bbox_inches="tight")
    figures.append(fig)
    saved.append(p)

    # ---- Fig 5: grism snippets per source
    img = {
        "data": res.observed_grism,
        "model": res.model_grism,
        "residual": res.residual_image,
    }
    fig, axes = plt.subplots(
        3, 5, figsize=(18, 6), width_ratios=[1, 1, 1, 1, 0.08]
    )
    for axes_, kind in zip(axes, img):
        image = img[kind]
        _im = None
        for ax, i in zip(axes_, picks):
            subimage = trace_snippet(image, res.operator, i, win=50)
            if kind == "residual":
                norm = colors.CenteredNorm(vcenter=0, halfrange=0.05)
                cmap = "coolwarm"
            else:
                norm = _safe_norm(image, "linear", percs=(80, 99))
                cmap = "magma"
            _im = ax.imshow(
                subimage + 1e-5, origin="lower", cmap=cmap, norm=norm
            )
        plt.colorbar(_im, cax=axes_[-1])
    for i, ax in zip(picks, axes[0]):
        ax.set_title(f"Source {i}", fontsize="large", fontweight="bold")
    for kind_, ax_ in zip(img, axes[:, 0]):
        ax_.set_ylabel(kind_, fontsize="large", fontweight="bold")
    for ax in axes[:-1, :-1].ravel():
        plt.setp(ax.get_xticklabels(), visible=False)
    for ax in axes[:, 1:-1].ravel():
        plt.setp(ax.get_yticklabels(), visible=False)
    p = os.path.join(outdir, f"fig5_{band}.png")
    fig.savefig(p, bbox_inches="tight")
    figures.append(fig)
    saved.append(p)

    if not close_figures:
        return figures, saved
    else:
        [plt.close(fig) for fig in figures]
        return saved


def make_all_review_figures(
    bands=("F115W", "F150W", "F200W"), outdir="figures", **kwargs
):
    """Run every band and write all review figures.

    Takes a few minutes (one fit per band).
    """
    os.makedirs(outdir, exist_ok=True)
    for band in bands:
        print(f"[review] {band} ...", flush=True)
        res = run_band(band)
        make_review_figures(res, band, outdir=outdir, **kwargs)


# %% Cell - run the analysis on F150W

res = run_band("F150W", max_iter=200)

# %% Cell - preliminary figures for diagnostics

fig, axes = plt.subplots(1, 3, figsize=(16, 5), sharex=True, sharey=True)
for ax, img, title in zip(
    axes,
    [res.observed_grism, res.model_grism, res.residual_image],
    ["data", "model", "residual / model"],
):
    if title == "residual / model":
        vmin, vmax = np.nanpercentile(img, [16, 84])
        cmap = "RdBu"
        norm = colors.CenteredNorm(vcenter=0, halfrange=0.05)
    else:
        vmin, vmax = np.nanpercentile(res.observed_grism, [16, 84])
        cmap = "gray"
        norm = colors.AsinhNorm(vmin=vmin, vmax=vmax)
    im_ = ax.imshow(img, origin="lower", cmap=cmap, norm=norm)
    fig.colorbar(im_, ax=ax)
    ax.set_title(title)
plt.tight_layout()
plt.savefig(Path("figures") / "tmp_sim_residual_image.png")

rng = np.random.default_rng(7)
# take the isolated spectra (according to isolation criterion)
# pick a random isolated spectrum within those
isolated_indices = np.where(res.other["is_isolated"])[0]
source_index = int(rng.choice(isolated_indices))

cut_data = trace_snippet(res.observed_grism, res.operator, source_index, win=7)
cut_model = trace_snippet(res.model_grism, res.operator, source_index, win=7)

_, axes = plt.subplots(1, 3, figsize=(12, 4), sharex=True, sharey=True)
axes = axes.flatten()

vn, vx = np.nanpercentile(cut_data, (20, 99))
norm = colors.AsinhNorm(vmin=vn, vmax=vx)
norm = colors.LogNorm(vmin=vn, vmax=vx)
im = axes[0].imshow(
    cut_data,
    origin="lower",
    cmap="gray",
    norm=norm,
)
plt.colorbar(im, ax=axes[0], orientation="horizontal")

im = axes[1].imshow(
    np.where(cut_model > 0, cut_model, 1e-10),
    origin="lower",
    cmap="gray",
    norm=norm,
)
plt.colorbar(im, ax=axes[1], orientation="horizontal")

scale_zoom = max(float(np.nanpercentile(cut_data[cut_data > 0], 99)), 1.0)
frac_residual_image = (cut_data - cut_model) / scale_zoom
im = axes[2].imshow(
    frac_residual_image,
    origin="lower",
    cmap="RdBu",
    norm=colors.CenteredNorm(vcenter=0, halfrange=0.05),
)
plt.colorbar(im, ax=axes[2], orientation="horizontal")

for ax, title in zip(axes, ["Data", "Model", "Residual / p99(obs)"]):
    ax.set_title(title)

plt.tight_layout()
plt.suptitle(
    f"Source {source_index + 1}", y=0.6, fontsize="large", fontweight="bold"
)
plt.savefig(
    Path("figures") / "tmp_sim_residual_image_zoom_source.png",
    bbox_inches="tight",
)


# %% Cell - complete set of figures for the N brightest isolated sources
make_review_figures(res, "F150W", outdir="figures", close_figures=False)


# %% Cell - set of figures for N isolated sources picked randomly
make_review_figures(
    res, "F150W", outdir="figures", close_figures=False, seed=42
)
# %% Cell - set of figures for all bands; This runs the fit per band too.

make_all_review_figures()
